### ISSUE TITLE
[FEAT] 판매자의 주문 내역 관리 기능

### ISSUE THREAD

**Issue by summit45** [28th-meetup/28th_Meetup_BE#30]
## ✏️ Description 
구매자가 주문을 했을 때, 판매자가 해당 주문 내역을 관리하는 페이지

## 📝 ToDo
- [x] 특정 가게의 모든 메뉴 가져오는 api 기능 구현
- [x] 특정 지역내의 TOP10 메뉴 가져오는 api 기능 구현
- [x] 카테고리별 메뉴 조회하는 api 기능 구현
- [x] 주문 내역 상세조회하는 api 기능 구현
- [x] 특정 가게의 특정 상태의 주문내역을 조회하는 api 기능 구현
- [x] 판매자가 주문 상태 변경하는 api 기능 구현

## ETC

**Additional context**
