### ISSUE TITLE
[FIX] 회원가입 API 변경사항

### ISSUE THREAD

**Issue by summit45** [28th-meetup/28th_Meetup_BE#37]
## ✏️ Description 
설명을 작성하세요.

## 📝 ToDo
- [x] 회원 가입시 국가번호 추가
- [x] 회원 가입시 주소 삭제
- [x] 닉네임 중복여부를 위한 API 생성

## ETC

**Additional context**
